listen_address: "::"
listen_port: 8080
debug_mode: false
test_port: 0
network_type: "tcp6"
max_timeout: 30
auth:
  type: "credentials"
  credentials:
    username: "username"
    password: "password"
  redis:
    dsn: "redis://localhost:6379"
bind_prefixes:
  - "2a14:dead:beef::1/48"
  - "2a14:dead:feed::1/48"
enable_fallback: true
fallback_prefixes:
  - "1.2.3.4/32"
located_prefixes:
  us:
    - 2a14:dead:beef::/48
  uk:
    - 2a14:dead:feed::/48
replace_ips:
  "1.2.3.0/24": "2a14:dead:beef::"
deleted_headers:
  - "Proxy-Authorization"
  - "Proxy-Connection"
